
data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture        = "x86_64"
    name                = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64*"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  profile     = "${var.profile}"
  region      = "${var.region}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

# template: hcl2_upgrade:4:98: executing "hcl2_upgrade" at <clean_resource_name>: error calling clean_resource_name: unhandled "clean_resource_name" call:
# there is no way to automatically upgrade the "clean_resource_name" call.
# Please manually upgrade to use custom validation rules, `replace(string, substring, replacement)` or `regex_replace(string, substring, replacement)`
# Visit https://packer.io/docs/templates/hcl_templates/variables#custom-validation-rules , https://www.packer.io/docs/templates/hcl_templates/functions/string/replace or https://www.packer.io/docs/templates/hcl_templates/functions/string/regex_replace for more infos.

source "amazon-ebs" "autogenerated_1" {
  ami_description = "{{user `project`}}-{{user `env`}}"
  ami_name        = "{{user `project`}}-ami-{{user `env`}}-{{isotime | clean_resource_name}}"
  instance_type   = "{{user `instance_type`}}"
  launch_block_device_mappings {
    delete_on_termination = true
    device_name           = "/dev/sda1"
    volume_size           = "{{user `volume_size`}}"
    volume_type           = "gp2"
  }
  profile      = "{{user `profile`}}"
  region       = "{{user `region`}}"
  source_ami   = "{{ data `amazon-ami.autogenerated_1.id` }}"
  ssh_timeout  = "10m"
  ssh_username = "ubuntu"
  tags = {
    Environment = "{{user `env`}}"
    Name        = "{{user `project`}}-{{user `env`}}-{{isotime | clean_resource_name}}"
    Packer      = "true"
    Stage       = "{{user `env`}}"
    Type        = ""
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    execute_command = "{{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    inline          = ["set -eux", "apt-add-repository ppa:ansible/ansible-2.8", "apt-get -y update", "apt-get -y install python-minimal python-apt", "apt-get -y install ansible"]
  }
}
