---
- name: Provision Image
  hosts: default
  remote_user: ubuntu

  tasks:
    - name: Install nginx
      become: yes
      apt:
        update_cache: yes
        name: nginx
        state: latest
    - name: Start nginx
      become: yes
      service:
        name: nginx
        state: started
    - name: Install curl
      become: yes
      apt:
        name: curl
    - name: Add node source repo
      shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"
    - name: Add yarn source repo
      shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
    - name: Write yarn source to source list
      shell: "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
    - name: Install ruby dependencies
      become: yes
      apt:
        update_cache: yes
        pkg:
          - git-core
          - zlib1g-dev
          - build-essential
          - libssl-dev
          - libreadline-dev
          - libyaml-dev
          - libsqlite3-dev
          - sqlite3
          - libxml2-dev
          - libxslt1-dev
          - libcurl4-openssl-dev
          - software-properties-common
          - libffi-dev
          - nodejs
          - yarn
        state: present
    - name: Install rvm dependencies
      become: yes
      apt:
        pkg:
          - libgdbm-dev
          - libncurses5-dev
          - automake
          - libtool
          - bison
          - libffi-dev
    - name: Add key server
      shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
    - name: Unset rvm
      shell: "unset rvm_path"
    - name: Install rvm
      shell: "curl -sSL https://get.rvm.io | bash -s stable"
    - name: Source rvm
      shell: source /home/ubuntu/.rvm/scripts/rvm
      args:
        executable: /bin/bash
    - name: Install ruby
      shell: "rvm install ruby 3.0.0"
    - name: Use ruby as default
      shell: "rvm use 3.0.0 --default"
      args:
        executable: /bin/bash
    - name: Install bundler
      shell: "gem install bundler"
      args:
        executable: /bin/bash
    - name: Install rails
      shell: "gem install rails -v 6.1.1"
      args:
        executable: /bin/bash
